id: I6D9002B6
legacy_id: P000348
ocr_import_info:
  bdrc_scan_id: W26036
  source: bdrc
  ocr_info:
    timestamp: '2020-03-14T10:17:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:22:16.541619+00:00'
last_modified: 2022-09-02 14:22:29.741346
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W26036
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26036
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྡོམ་པ་གསུམ་གྱི་རྒྱན་ཅེས་བྱ་བའི་བསྟན་བཅོས་ཀྱི་མཆན་འགྲེལ་པད་དཀར་ཞལ་ལུང་།
  author: འབྲུག་རྗེ་མཁན་པོ ༦༩་དགེ་འདུན་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.781896232750421
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I4334:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4334
      total_pages: 416
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4334.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.781896232750421
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
